"""Rebuild app/data/icd11_mms.tsv.gz from WHO's published MMS linearization.

The ICD-11 API (id.who.int) needs OAuth client credentials we do not have, but
WHO also publishes each release as a **public static file** — the "Simple
Tabulation" of the Mortality and Morbidity Statistics linearization. That file
is the authoritative list of codes and titles, so the catalog is generated from
it rather than typed out by hand. Do not hand-edit the generated .tsv.gz; edit
this script and re-run it.

    python scripts/build_icd11_catalog.py                 # current release
    python scripts/build_icd11_catalog.py --release 2024-01
    python scripts/build_icd11_catalog.py --zip ./SimpleTabulation-ICD-11-MMS-en.zip

Use --zip when the network path is unavailable or TLS is intercepted; download
the same URL by hand (curl -LO) and point the script at the file.

Aliases (lay terms and abbreviations like "ESRD" or "G6PD") are NOT in the WHO
file and live in app/services/icd11_catalog.py, not here.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

DEFAULT_RELEASE = "2025-01"
SOURCE_URL = (
    "https://icdcdn.who.int/static/releasefiles/{release}/"
    "SimpleTabulation-ICD-11-MMS-en.zip"
)
OUT_PATH = Path(__file__).resolve().parent.parent / "app" / "data" / "icd11_mms.tsv.gz"

# Columns in the WHO simple-tabulation TSV that we keep.
_COL_CODE = 2
_COL_TITLE = 4
_COL_KIND = 5
_COL_RESIDUAL = 7
_COL_CHAPTER = 8
_COL_LEAF = 10


def fetch(release: str) -> bytes:
    url = SOURCE_URL.format(release=release)
    print(f"→ {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=120) as resp:
        if resp.status != 200:
            raise SystemExit(f"WHO returned HTTP {resp.status} for {url}")
        return resp.read()


def extract_rows(zip_bytes: bytes) -> tuple[list[tuple[str, ...]], dict[str, str], str]:
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        name = next(n for n in zf.namelist() if n.endswith("-MMS-en.txt"))
        raw = zf.read(name).decode("utf-8-sig")

    reader = csv.reader(io.StringIO(raw), delimiter="\t", quotechar='"')
    header = next(reader)
    # The WHO file carries its build stamp in the last header cell.
    version = header[-1].strip() if header else "unknown"

    rows: list[tuple[str, ...]] = []
    chapters: dict[str, str] = {}
    for row in reader:
        if len(row) <= _COL_LEAF:
            continue
        code = row[_COL_CODE].strip()
        if not code:
            # Chapters and blocks carry no code — they are groupings. Keep the
            # chapter titles (so they need not be re-typed) and drop the blocks.
            if row[_COL_KIND].strip() == "chapter":
                chapters[row[_COL_CHAPTER].strip()] = (
                    row[_COL_TITLE].strip().lstrip("- ").strip()
                )
            continue
        # Titles are indented with "- " per depth level; strip the indent only.
        title = row[_COL_TITLE].strip().lstrip("- ").strip()
        if not title:
            continue
        rows.append((
            code,
            title,
            row[_COL_CHAPTER].strip(),
            "1" if row[_COL_LEAF].strip().lower() == "true" else "0",
            "1" if row[_COL_RESIDUAL].strip().lower() == "true" else "0",
            row[_COL_KIND].strip(),
        ))
    return rows, chapters, version


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--release", default=DEFAULT_RELEASE)
    ap.add_argument(
        "--zip",
        type=Path,
        help="use an already-downloaded SimpleTabulation zip instead of fetching",
    )
    args = ap.parse_args()

    zip_bytes = args.zip.read_bytes() if args.zip else fetch(args.release)
    rows, chapters, version = extract_rows(zip_bytes)
    if len(rows) < 10_000:
        raise SystemExit(f"refusing to write a suspiciously small catalog ({len(rows)} rows)")

    buf = io.StringIO()
    buf.write(f"# ICD-11 MMS {args.release} — {version}\n")
    buf.write("# generated by scripts/build_icd11_catalog.py — do not hand-edit\n")
    for num, title in sorted(chapters.items()):
        buf.write(f"#chapter\t{num}\t{title}\n")
    writer = csv.writer(buf, delimiter="\t", lineterminator="\n")
    writer.writerow(["code", "title", "chapter", "is_leaf", "is_residual", "kind"])
    writer.writerows(rows)

    payload = buf.getvalue().encode("utf-8")
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # mtime=0 so rebuilding an unchanged release produces an identical file.
    with gzip.GzipFile(OUT_PATH, "wb", compresslevel=9, mtime=0) as fh:
        fh.write(payload)

    print(
        f"wrote {OUT_PATH.relative_to(OUT_PATH.parents[2])}: "
        f"{len(rows)} codes, {len(chapters)} chapters, "
        f"{OUT_PATH.stat().st_size / 1024:.0f} KB gz ({version})",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
