"""AI-powered Diagnostics Engine.

This is the core intelligence layer that powers:
 1. Symptom-based differential diagnosis (ICD-10 coded)
 2. Lab-correlated diagnostic refinement
 3. Risk-factor & history-aware assessment
 4. Proactive screening recommendations
 5. Urgency triage (emergency / urgent / routine / monitoring)

The engine collects all available patient data — symptoms, vitals, labs,
medications, history, demographics, lifestyle — and produces structured
diagnostic assessments with ICD-10 codes, confidence scores, and
evidence-based next-step recommendations.

IMPORTANT: All outputs carry a disclaimer that this is clinical decision
support, NOT a replacement for professional medical evaluation.
"""

import json
import os
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

import httpx
from sqlalchemy import desc, select, and_
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.user import User
from app.models.conditions import HealthCondition, SymptomLog, IllnessLog
from app.models.chronic_conditions import ChronicCondition
from app.models.labs import LabResult
from app.models.medications import Medication
from app.models.vitals import VitalsLog
from app.services.icd10_catalog import (
    ICD10_CATALOG,
    search_icd10,
    get_codes_by_symptoms,
    get_icd10_by_code,
    ICD10Code,
)


# ── Urgency levels ────────────────────────────────────────────────────

URGENCY_LEVELS = {
    "emergency":  {"label": "Emergency", "description": "Seek immediate emergency care (call 911 / go to ER)", "color": "#e53e3e"},
    "urgent":     {"label": "Urgent",    "description": "See a healthcare provider within 24-48 hours", "color": "#ed8936"},
    "soon":       {"label": "Soon",      "description": "Schedule an appointment within 1-2 weeks", "color": "#ecc94b"},
    "routine":    {"label": "Routine",   "description": "Discuss at your next routine visit", "color": "#48bb78"},
    "monitoring": {"label": "Monitor",   "description": "Continue monitoring; log symptoms if they change", "color": "#4299e1"},
}

# ── Red-flag symptom patterns (always flag as urgent/emergency) ───────

RED_FLAG_SYMPTOMS = {
    "emergency": [
        "chest pain", "crushing chest pressure", "sudden severe headache",
        "difficulty breathing", "sudden weakness one side", "facial droop",
        "slurred speech", "loss of consciousness", "seizure", "severe bleeding",
        "anaphylaxis", "suicidal ideation", "suicidal thoughts",
        "sudden vision loss", "coughing blood", "severe abdominal pain sudden onset",
    ],
    "urgent": [
        "high fever", "blood in stool", "blood in urine", "unexplained weight loss",
        "persistent vomiting", "severe dehydration", "confusion", "worsening shortness of breath",
        "new lump", "sudden swelling", "severe allergic reaction",
        "persistent chest pain", "high blood pressure crisis",
    ],
}


class DiagnosticsEngine:
    """AI-powered clinical decision support engine.

    Combines rule-based ICD-10 matching with LLM-powered differential
    diagnosis reasoning.  All outputs include ICD-10 codes, confidence
    scores, supporting evidence, and recommended next steps.
    """

    DISCLAIMER = (
        "This assessment is generated by an AI clinical decision support system "
        "and is for informational purposes only. It does NOT constitute a medical "
        "diagnosis. Always consult a qualified healthcare professional for proper "
        "evaluation and treatment."
    )

    def __init__(
        self,
        db: AsyncSession,
        api_key: Optional[str] = None,
        provider: str = "openai",
    ):
        self.db = db
        self.provider = provider
        self.api_key = api_key or os.getenv(
            "OPENAI_API_KEY" if provider == "openai" else "ANTHROPIC_API_KEY"
        )
        if provider == "openai":
            self.api_url = "https://api.openai.com/v1/chat/completions"
            self.model = os.getenv("OPENAI_MODEL", "gpt-4-turbo-preview")
        else:
            self.api_url = "https://api.anthropic.com/v1/messages"
            self.model = os.getenv("ANTHROPIC_MODEL", "claude-3-5-sonnet-20241022")

    # ══════════════════════════════════════════════════════════════
    # PUBLIC API
    # ══════════════════════════════════════════════════════════════

    async def assess_symptoms(
        self,
        user: User,
        symptoms: List[Dict[str, Any]],
        additional_context: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Run a full diagnostic assessment from reported symptoms.

        Args:
            user: The patient
            symptoms: List of dicts with keys:
                - name (str): symptom name
                - severity (int 1-10): optional severity
                - duration (str): optional duration e.g. "3 days"
                - body_part (str): optional location
                - quality (str): optional e.g. "sharp", "dull"
                - pattern (str): optional e.g. "constant", "intermittent"
            additional_context: Free-text additional info from patient

        Returns:
            Structured diagnostic assessment dict.
        """
        # 1. Gather all patient context
        patient_context = await self._gather_patient_context(user)

        # 2. Rule-based initial screening
        symptom_names = [s["name"] for s in symptoms]
        urgency = self._assess_urgency(symptom_names)
        icd_matches = get_codes_by_symptoms(symptom_names, min_match=1)

        # 3. Build rule-based differential
        rule_based_differential = self._build_rule_based_differential(
            symptoms, icd_matches, patient_context
        )

        # 4. LLM-powered deep analysis
        llm_assessment = await self._llm_diagnostic_reasoning(
            symptoms, patient_context, rule_based_differential, additional_context
        )

        # 5. Compose final assessment
        assessment = {
            "assessment_id": f"DX-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{user.id}",
            "patient_id": user.id,
            "assessed_at": datetime.now(timezone.utc).isoformat(),
            "urgency": urgency,
            "reported_symptoms": symptoms,
            "differential_diagnoses": llm_assessment.get("differentials", rule_based_differential[:10]),
            "primary_impression": llm_assessment.get("primary_impression", "Assessment requires further evaluation"),
            "supporting_evidence": llm_assessment.get("supporting_evidence", []),
            "contradicting_factors": llm_assessment.get("contradicting_factors", []),
            "recommended_actions": llm_assessment.get("recommended_actions", []),
            "recommended_tests": llm_assessment.get("recommended_tests", []),
            "red_flags": llm_assessment.get("red_flags", []),
            "risk_factors_identified": llm_assessment.get("risk_factors", []),
            "follow_up_timeline": llm_assessment.get("follow_up_timeline", "As advised by healthcare provider"),
            "patient_education": llm_assessment.get("patient_education", []),
            "disclaimer": self.DISCLAIMER,
        }

        return assessment

    async def proactive_screening(self, user: User) -> Dict[str, Any]:
        """Analyze patient's complete profile for proactive health screening.

        Reviews demographics, family history, lifestyle, vitals, labs,
        and existing conditions to identify:
         - Overdue screenings
         - Elevated risk conditions
         - Emerging patterns
         - Preventive recommendations
        """
        patient_context = await self._gather_patient_context(user)
        recommendations = self._rule_based_screening(patient_context)

        # Enhance with LLM analysis
        llm_screening = await self._llm_proactive_screening(patient_context)

        return {
            "screening_id": f"SCR-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{user.id}",
            "patient_id": user.id,
            "screened_at": datetime.now(timezone.utc).isoformat(),
            "risk_profile": llm_screening.get("risk_profile", recommendations.get("risk_profile", {})),
            "recommended_screenings": llm_screening.get("recommended_screenings", recommendations.get("screenings", [])),
            "emerging_patterns": llm_screening.get("emerging_patterns", []),
            "preventive_actions": llm_screening.get("preventive_actions", recommendations.get("preventive", [])),
            "lifestyle_modifications": llm_screening.get("lifestyle_modifications", []),
            "disclaimer": self.DISCLAIMER,
        }

    async def correlate_lab_results(
        self,
        user: User,
        lab_result_ids: Optional[List[int]] = None,
    ) -> Dict[str, Any]:
        """Correlate lab results with symptoms and conditions for diagnostic insights."""
        patient_context = await self._gather_patient_context(user)

        # Get specific lab results or recent ones
        if lab_result_ids:
            stmt = select(LabResult).where(
                and_(LabResult.user_id == user.id, LabResult.id.in_(lab_result_ids))
            )
        else:
            stmt = (
                select(LabResult)
                .where(LabResult.user_id == user.id)
                .order_by(desc(LabResult.test_date))
                .limit(20)
            )
        result = await self.db.execute(stmt)
        labs = result.scalars().all()

        lab_data = [
            {
                "test_name": lab.test_name,
                "value": lab.value,
                "unit": lab.unit,
                "reference_range": f"{lab.reference_range_low}-{lab.reference_range_high}" if lab.reference_range_low else None,
                "is_abnormal": lab.is_abnormal,
                "test_date": str(lab.test_date) if lab.test_date else None,
                "loinc_code": lab.loinc_code,
            }
            for lab in labs
        ]

        abnormal_labs = [l for l in lab_data if l.get("is_abnormal")]

        # LLM correlation analysis
        correlation = await self._llm_lab_correlation(
            lab_data, abnormal_labs, patient_context
        )

        return {
            "correlation_id": f"LAB-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{user.id}",
            "patient_id": user.id,
            "analyzed_at": datetime.now(timezone.utc).isoformat(),
            "labs_analyzed": len(lab_data),
            "abnormal_count": len(abnormal_labs),
            "abnormal_labs": abnormal_labs,
            "diagnostic_correlations": correlation.get("correlations", []),
            "possible_conditions": correlation.get("possible_conditions", []),
            "recommended_follow_up_tests": correlation.get("follow_up_tests", []),
            "clinical_significance": correlation.get("clinical_significance", "Requires professional interpretation"),
            "disclaimer": self.DISCLAIMER,
        }

    async def get_condition_detail(self, icd10_code: str) -> Optional[Dict[str, Any]]:
        """Get detailed information about a condition by ICD-10 code."""
        code_obj = get_icd10_by_code(icd10_code)
        if not code_obj:
            return None

        return {
            "icd10_code": code_obj.code,
            "title": code_obj.title,
            "chapter": code_obj.chapter,
            "chapter_title": self._get_chapter_title(code_obj.chapter),
            "category": code_obj.category,
            "body_system": code_obj.body_system,
            "common_symptoms": code_obj.common_symptoms,
            "risk_factors": code_obj.risk_factors,
            "is_billable": code_obj.is_billable,
        }

    # ══════════════════════════════════════════════════════════════
    # PATIENT CONTEXT GATHERING
    # ══════════════════════════════════════════════════════════════

    async def _gather_patient_context(self, user: User) -> Dict[str, Any]:
        """Build comprehensive patient context from all data sources."""
        cutoff = datetime.now(timezone.utc) - timedelta(days=90)

        # Parallel queries
        conditions_stmt = select(HealthCondition).where(
            and_(HealthCondition.user_id == user.id, HealthCondition.status.in_(["active", "managed"]))
        )
        chronic_stmt = select(ChronicCondition).where(
            and_(ChronicCondition.user_id == user.id, ChronicCondition.is_active == True)
        )
        symptoms_stmt = (
            select(SymptomLog)
            .where(and_(SymptomLog.user_id == user.id, SymptomLog.created_at >= cutoff))
            .order_by(desc(SymptomLog.created_at))
            .limit(20)
        )
        meds_stmt = select(Medication).where(
            and_(Medication.user_id == user.id, Medication.is_active == True)
        )
        vitals_stmt = (
            select(VitalsLog)
            .where(VitalsLog.user_id == user.id)
            .order_by(desc(VitalsLog.created_at))
            .limit(5)
        )
        labs_stmt = (
            select(LabResult)
            .where(and_(LabResult.user_id == user.id, LabResult.test_date >= cutoff.date()))
            .order_by(desc(LabResult.test_date))
            .limit(20)
        )
        illness_stmt = (
            select(IllnessLog)
            .where(and_(IllnessLog.user_id == user.id, IllnessLog.created_at >= cutoff))
            .order_by(desc(IllnessLog.created_at))
            .limit(10)
        )

        conditions_r = await self.db.execute(conditions_stmt)
        chronic_r = await self.db.execute(chronic_stmt)
        symptoms_r = await self.db.execute(symptoms_stmt)
        meds_r = await self.db.execute(meds_stmt)
        vitals_r = await self.db.execute(vitals_stmt)
        labs_r = await self.db.execute(labs_stmt)
        illness_r = await self.db.execute(illness_stmt)

        conditions = conditions_r.scalars().all()
        chronic = chronic_r.scalars().all()
        symptoms = symptoms_r.scalars().all()
        medications = meds_r.scalars().all()
        vitals = vitals_r.scalars().all()
        labs = labs_r.scalars().all()
        illnesses = illness_r.scalars().all()

        # Calculate age
        age = None
        if user.date_of_birth:
            try:
                dob = datetime.strptime(user.date_of_birth, "%Y-%m-%d")
                today = datetime.now()
                age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
            except Exception:
                pass

        bmi = None
        if user.height_cm and user.current_weight_kg:
            h = user.height_cm / 100
            bmi = round(user.current_weight_kg / (h * h), 1)

        context = {
            "demographics": {
                "age": age,
                "gender": user.gender,
                "gender_at_birth": getattr(user, "gender_at_birth", None),
                "blood_type": user.blood_type,
                "height_cm": user.height_cm,
                "weight_kg": user.current_weight_kg,
                "bmi": bmi,
                "country": getattr(user, "country", None),
                "ethnicity_context": getattr(user, "country", None),  # relevant for genetic risk
            },
            "allergies": getattr(user, "allergies", None),
            "family_history": getattr(user, "family_history", None),
            "lifestyle": {
                "smoking_status": getattr(user, "smoking_status", None),
                "alcohol_consumption": getattr(user, "alcohol_consumption", None),
                "activity_level": getattr(user, "activity_level", None),
                "occupation": getattr(user, "occupation", None),
                "stress_level": getattr(user, "stress_level", None),
                "sleep_schedule": getattr(user, "sleep_schedule", None),
            },
            "active_conditions": [
                {
                    "name": c.condition_name,
                    "icd10": c.icd10_code,
                    "category": c.category,
                    "severity": c.severity,
                    "since": c.diagnosis_date.isoformat() if c.diagnosis_date else None,
                }
                for c in conditions
            ],
            "chronic_conditions": [
                {
                    "name": c.condition_name,
                    "icd10": c.icd10_code,
                    "category": c.category.value if c.category else None,
                    "severity": c.severity.value if c.severity else None,
                    "stage": c.stage,
                }
                for c in chronic
            ],
            "recent_symptoms": [
                {
                    "name": s.symptom_name,
                    "severity": s.severity,
                    "body_part": s.body_part,
                    "date": s.created_at.isoformat() if s.created_at else None,
                }
                for s in symptoms
            ],
            "current_medications": [
                {
                    "name": m.name,
                    "dosage": m.dosage,
                    "frequency": m.frequency,
                }
                for m in medications
            ],
            "vitals": [
                {
                    "bp": f"{v.blood_pressure_systolic}/{v.blood_pressure_diastolic}" if v.blood_pressure_systolic else None,
                    "heart_rate": v.heart_rate_bpm,
                    "weight": v.weight_kg,
                    "date": v.created_at.isoformat() if v.created_at else None,
                }
                for v in vitals
            ],
            "recent_labs": [
                {
                    "test": l.test_name,
                    "value": l.value,
                    "unit": l.unit,
                    "abnormal": l.is_abnormal,
                    "date": str(l.test_date) if l.test_date else None,
                }
                for l in labs
            ],
            "recent_illnesses": [
                {
                    "name": i.illness_name,
                    "type": i.illness_type,
                    "onset": i.onset_date.isoformat() if i.onset_date else None,
                    "status": i.status,
                }
                for i in illnesses
            ],
        }
        return context

    # ══════════════════════════════════════════════════════════════
    # RULE-BASED ENGINE
    # ══════════════════════════════════════════════════════════════

    def _assess_urgency(self, symptom_names: List[str]) -> Dict[str, Any]:
        """Determine urgency level from symptoms."""
        symptom_lower = [s.lower() for s in symptom_names]
        joined = " ".join(symptom_lower)

        for red_flag in RED_FLAG_SYMPTOMS["emergency"]:
            if red_flag in joined:
                return {
                    **URGENCY_LEVELS["emergency"],
                    "trigger": red_flag,
                    "level": "emergency",
                }

        for red_flag in RED_FLAG_SYMPTOMS["urgent"]:
            if red_flag in joined:
                return {
                    **URGENCY_LEVELS["urgent"],
                    "trigger": red_flag,
                    "level": "urgent",
                }

        # Default based on symptom count and severity keywords
        severity_words = {"severe", "intense", "extreme", "unbearable", "worst"}
        if any(w in joined for w in severity_words):
            return {**URGENCY_LEVELS["urgent"], "trigger": "severity_keywords", "level": "urgent"}

        if len(symptom_names) >= 4:
            return {**URGENCY_LEVELS["soon"], "trigger": "multiple_symptoms", "level": "soon"}

        return {**URGENCY_LEVELS["routine"], "trigger": "standard_assessment", "level": "routine"}

    def _build_rule_based_differential(
        self,
        symptoms: List[Dict[str, Any]],
        icd_matches: List[tuple],
        patient_context: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Build initial differential diagnosis from ICD-10 catalog matching."""
        differential = []
        symptom_names = [s["name"].lower() for s in symptoms]

        for code_obj, match_count in icd_matches[:15]:
            # Calculate confidence based on multiple factors
            confidence = self._calculate_match_confidence(
                code_obj, symptom_names, match_count, patient_context
            )

            differential.append({
                "icd10_code": code_obj.code,
                "condition": code_obj.title,
                "body_system": code_obj.body_system,
                "confidence": round(confidence, 2),
                "matched_symptoms": [s for s in code_obj.common_symptoms if s.lower() in " ".join(symptom_names)],
                "risk_factor_match": self._check_risk_factors(code_obj, patient_context),
                "source": "rule_based",
            })

        differential.sort(key=lambda d: d["confidence"], reverse=True)
        return differential

    def _calculate_match_confidence(
        self,
        code_obj: ICD10Code,
        symptom_names: List[str],
        match_count: int,
        patient_context: Dict[str, Any],
    ) -> float:
        """Calculate a confidence score (0.0 - 1.0) for a potential diagnosis."""
        total_code_symptoms = len(code_obj.common_symptoms) or 1

        # Base: symptom overlap ratio
        base_score = match_count / total_code_symptoms

        # Boost: risk factor alignment
        risk_match = self._check_risk_factors(code_obj, patient_context)
        risk_boost = len(risk_match) * 0.05

        # Boost: existing related conditions
        existing_conditions = [
            c.get("name", "").lower()
            for c in patient_context.get("active_conditions", [])
            + patient_context.get("chronic_conditions", [])
        ]
        condition_boost = 0.0
        for cond_name in existing_conditions:
            if any(word in code_obj.title.lower() for word in cond_name.split()):
                condition_boost = 0.1
                break

        # Boost: family history
        family = (patient_context.get("family_history") or "").lower()
        family_boost = 0.0
        if family:
            condition_words = code_obj.title.lower().split()
            if any(w in family for w in condition_words if len(w) > 4):
                family_boost = 0.05

        # Demographic modifiers
        demo = patient_context.get("demographics", {})
        demo_boost = 0.0
        age = demo.get("age")
        gender = (demo.get("gender") or "").lower()

        for rf in code_obj.risk_factors:
            rf_lower = rf.lower()
            if age and "age" in rf_lower:
                if ">45" in rf_lower and age > 45:
                    demo_boost += 0.03
                elif ">50" in rf_lower and age > 50:
                    demo_boost += 0.03
                elif ">60" in rf_lower and age > 60:
                    demo_boost += 0.03
            if "female" in rf_lower and gender in ("f", "female"):
                demo_boost += 0.02
            if "male" in rf_lower and gender in ("m", "male"):
                demo_boost += 0.02
            if "african" in rf_lower:
                country = (demo.get("country") or "").lower()
                if any(c in country for c in ["ghana", "nigeria", "senegal", "kenya", "south africa", "ethiopia"]):
                    demo_boost += 0.03
            if "obesity" in rf_lower:
                bmi = demo.get("bmi")
                if bmi and bmi >= 30:
                    demo_boost += 0.05

        total = min(base_score + risk_boost + condition_boost + family_boost + demo_boost, 0.95)
        return total

    def _check_risk_factors(
        self, code_obj: ICD10Code, patient_context: Dict[str, Any]
    ) -> List[str]:
        """Check which risk factors match this patient."""
        matched = []
        if not code_obj.risk_factors:
            return matched

        demo = patient_context.get("demographics", {})
        lifestyle = patient_context.get("lifestyle", {})
        family = (patient_context.get("family_history") or "").lower()

        for rf in code_obj.risk_factors:
            rf_lower = rf.lower()
            # Smoking
            if "smoking" in rf_lower and lifestyle.get("smoking_status") in ("current", "former"):
                matched.append(rf)
            # Obesity
            elif "obesity" in rf_lower and demo.get("bmi") and demo["bmi"] >= 30:
                matched.append(rf)
            # Sedentary
            elif "sedentary" in rf_lower and lifestyle.get("activity_level") == "sedentary":
                matched.append(rf)
            # Family history
            elif "family history" in rf_lower and family:
                # Check if the condition type is in family history
                for word in code_obj.title.lower().split():
                    if len(word) > 4 and word in family:
                        matched.append(rf)
                        break
            # Alcohol
            elif "alcohol" in rf_lower and lifestyle.get("alcohol_consumption") in ("heavy", "moderate"):
                matched.append(rf)
            # Age
            elif "age" in rf_lower:
                age = demo.get("age")
                if age:
                    if ">45" in rf_lower and age > 45:
                        matched.append(rf)
                    elif ">50" in rf_lower and age > 50:
                        matched.append(rf)
                    elif ">60" in rf_lower and age > 60:
                        matched.append(rf)
                    elif ">65" in rf_lower and age > 65:
                        matched.append(rf)

        return matched

    def _rule_based_screening(self, patient_context: Dict[str, Any]) -> Dict[str, Any]:
        """Generate rule-based screening recommendations."""
        demo = patient_context.get("demographics", {})
        lifestyle = patient_context.get("lifestyle", {})
        family = (patient_context.get("family_history") or "").lower()
        age = demo.get("age")
        gender = (demo.get("gender") or "").lower()
        bmi = demo.get("bmi")

        screenings = []
        risk_profile = {}
        preventive = []

        # ── Age & gender-based screenings ──
        if age:
            if age >= 45:
                screenings.append({
                    "screening": "Diabetes screening (HbA1c or fasting glucose)",
                    "icd10_code": "Z13.1",
                    "rationale": "Recommended for adults ≥45",
                    "frequency": "Every 3 years if normal",
                })
            if age >= 50:
                screenings.append({
                    "screening": "Colorectal cancer screening",
                    "icd10_code": "Z12.11",
                    "rationale": "USPSTF recommends starting at 45-50",
                    "frequency": "Every 10 years (colonoscopy) or per method",
                })
            if age >= 21 and gender in ("f", "female"):
                screenings.append({
                    "screening": "Cervical cancer screening (Pap smear)",
                    "icd10_code": "Z12.4",
                    "rationale": "Recommended for women 21-65",
                    "frequency": "Every 3 years (21-29) or every 5 years with HPV co-test (30-65)",
                })
            if age >= 40 and gender in ("f", "female"):
                screenings.append({
                    "screening": "Mammography (breast cancer screening)",
                    "icd10_code": "Z12.31",
                    "rationale": "Recommended for women starting at 40",
                    "frequency": "Every 1-2 years",
                })
            if age >= 50 and gender in ("m", "male"):
                screenings.append({
                    "screening": "Prostate cancer screening discussion (PSA)",
                    "icd10_code": "Z12.5",
                    "rationale": "Discuss with provider; higher risk if African descent or family history",
                    "frequency": "Discuss individually",
                })
            if age >= 18:
                screenings.append({
                    "screening": "Lipid panel (cholesterol screening)",
                    "icd10_code": "Z13.220",
                    "rationale": "Recommended for all adults; periodically",
                    "frequency": "Every 4-6 years if normal (more often if risk factors)",
                })
                screenings.append({
                    "screening": "Blood pressure screening",
                    "icd10_code": "Z13.6",
                    "rationale": "Recommended at every healthcare visit",
                    "frequency": "At least annually",
                })

        # ── Risk-factor based ──
        if bmi and bmi >= 30:
            risk_profile["obesity"] = {
                "level": "high",
                "bmi": bmi,
                "associated_risks": ["Type 2 diabetes", "Cardiovascular disease", "Sleep apnea", "Osteoarthritis"],
            }
            preventive.append("Weight management program — consider dietary counseling and structured exercise")

        if lifestyle.get("smoking_status") in ("current",):
            risk_profile["smoking"] = {"level": "high", "associated_risks": ["Lung cancer", "COPD", "Cardiovascular disease"]}
            preventive.append("Smoking cessation program — nicotine replacement therapy or medications available")

        if lifestyle.get("activity_level") == "sedentary":
            risk_profile["sedentary"] = {"level": "moderate", "associated_risks": ["Cardiovascular disease", "Obesity", "Diabetes"]}
            preventive.append("Increase physical activity — aim for 150 min/week moderate exercise")

        if "diabetes" in family:
            risk_profile["family_diabetes"] = {"level": "elevated", "associated_risks": ["Type 2 diabetes"]}
            if age and age < 45:
                screenings.append({
                    "screening": "Early diabetes screening (family history)",
                    "icd10_code": "Z13.1",
                    "rationale": "Family history of diabetes increases risk",
                    "frequency": "Every 3 years",
                })

        if "cancer" in family:
            risk_profile["family_cancer"] = {"level": "elevated"}
            preventive.append("Discuss family cancer history with provider for personalized screening schedule")

        if "hypertension" in family or "high blood pressure" in family:
            risk_profile["family_hypertension"] = {"level": "elevated", "associated_risks": ["Hypertension"]}

        # Sickle cell screening for African descent
        country = (demo.get("country") or "").lower()
        african_countries = {"ghana", "nigeria", "senegal", "kenya", "south africa", "ethiopia", "tanzania", "rwanda"}
        if any(c in country for c in african_countries):
            screenings.append({
                "screening": "Sickle cell trait / G6PD screening",
                "icd10_code": "Z13.0",
                "rationale": "Higher prevalence in African-descent populations",
                "frequency": "Once (genetic test)",
            })

        return {
            "risk_profile": risk_profile,
            "screenings": screenings,
            "preventive": preventive,
        }

    # ══════════════════════════════════════════════════════════════
    # LLM-POWERED REASONING
    # ══════════════════════════════════════════════════════════════

    async def _call_llm(self, messages: List[Dict[str, str]], temperature: float = 0.3, max_tokens: int = 4000) -> str:
        """Call the LLM through the ALAFIAModel router, requesting JSON output.

        Returns "" on failure so the rule-based path can proceed gracefully.
        """
        from app.services.alafia_model_service import alafia_chat, ALAFIAModelError
        try:
            return await alafia_chat(
                messages, temperature=temperature, max_tokens=max_tokens, json_mode=True
            )
        except ALAFIAModelError:
            return ""

    async def _llm_diagnostic_reasoning(
        self,
        symptoms: List[Dict[str, Any]],
        patient_context: Dict[str, Any],
        rule_based: List[Dict[str, Any]],
        additional_context: Optional[str],
    ) -> Dict[str, Any]:
        """Use LLM for deep diagnostic reasoning."""
        system_prompt = """You are an expert clinical decision support system. Your role is to assist
healthcare providers and patients by analyzing symptoms in context of the patient's
complete health profile. You produce STRUCTURED diagnostic assessments.

CRITICAL RULES:
1. Always generate ICD-10 codes for every differential diagnosis
2. Rank differentials by probability considering ALL patient context
3. Identify red flags immediately
4. Consider drug interactions with current medications
5. Factor in demographics (age, sex, ethnicity) for condition prevalence
6. Consider family history for genetic predispositions
7. Check if symptoms could be side effects of current medications
8. Always recommend professional follow-up
9. Be thorough but prioritize the most clinically significant conditions

Respond ONLY in valid JSON with this exact structure:
{
    "primary_impression": "string — most likely diagnosis with brief explanation",
    "differentials": [
        {
            "icd10_code": "string",
            "condition": "string — full condition name",
            "body_system": "string",
            "confidence": 0.0-1.0,
            "reasoning": "string — why this condition fits",
            "matched_symptoms": ["symptom1", "symptom2"],
            "risk_factor_match": ["risk1"],
            "source": "ai_enhanced"
        }
    ],
    "supporting_evidence": ["string — evidence supporting top diagnosis"],
    "contradicting_factors": ["string — what argues against top diagnosis"],
    "recommended_actions": ["string — immediate actions"],
    "recommended_tests": [
        {"test": "string", "rationale": "string", "urgency": "routine|urgent|stat"}
    ],
    "red_flags": ["string — critical warning signs to watch for"],
    "risk_factors": ["string — identified risk factors"],
    "follow_up_timeline": "string — when to follow up",
    "patient_education": ["string — key info for the patient"]
}"""

        user_prompt = f"""PATIENT CONTEXT:
{json.dumps(patient_context, indent=2, default=str)}

CURRENT SYMPTOMS:
{json.dumps(symptoms, indent=2)}

{f"ADDITIONAL CONTEXT FROM PATIENT: {additional_context}" if additional_context else ""}

INITIAL RULE-BASED MATCHES (refine these):
{json.dumps(rule_based[:8], indent=2)}

Provide a comprehensive diagnostic assessment. Consider:
- Symptom patterns and their temporal relationships
- Existing conditions that may explain symptoms
- Medication side effects as potential causes
- Age/sex/ethnicity-specific prevalences
- Family history implications
- Lifestyle factors (smoking, alcohol, activity, stress)
- Whether symptoms suggest complications of existing conditions"""

        raw = await self._call_llm([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ])

        if not raw:
            return {}

        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            # Try to extract JSON from response
            try:
                start = raw.index("{")
                end = raw.rindex("}") + 1
                return json.loads(raw[start:end])
            except (ValueError, json.JSONDecodeError):
                return {"primary_impression": raw[:500]}

    async def _llm_proactive_screening(self, patient_context: Dict[str, Any]) -> Dict[str, Any]:
        """Use LLM for proactive health screening analysis."""
        system_prompt = """You are a preventive medicine specialist AI. Analyze the patient's complete
health profile and identify:
1. Conditions they may be at elevated risk for
2. Overdue or recommended screenings
3. Emerging health patterns that warrant attention
4. Lifestyle modifications that could reduce risk
5. Potential drug interactions or medication concerns

Use ICD-10 codes where applicable. Consider evidence-based screening
guidelines (USPSTF, WHO, regional guidelines).

Respond ONLY in valid JSON:
{
    "risk_profile": {"condition": {"level": "low|moderate|high|critical", "rationale": "string"}},
    "recommended_screenings": [{"screening": "string", "icd10_code": "string", "rationale": "string", "frequency": "string", "priority": "high|medium|low"}],
    "emerging_patterns": ["string — patterns noticed in the data"],
    "preventive_actions": ["string — actionable prevention steps"],
    "lifestyle_modifications": [{"area": "string", "current": "string", "recommended": "string", "impact": "string"}]
}"""

        user_prompt = f"""COMPLETE PATIENT PROFILE:
{json.dumps(patient_context, indent=2, default=str)}

Perform a comprehensive preventive health analysis. Consider:
- Age-appropriate cancer screenings
- Cardiovascular risk assessment
- Metabolic syndrome indicators
- Mental health screening needs
- Immunization status considerations
- Bone density screening (if applicable)
- Vision and hearing screening
- Dental health implications
- Regional/ethnic predispositions (patient country: {patient_context.get('demographics', {}).get('country', 'unknown')})"""

        raw = await self._call_llm([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ])

        if not raw:
            return {}

        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            try:
                start = raw.index("{")
                end = raw.rindex("}") + 1
                return json.loads(raw[start:end])
            except (ValueError, json.JSONDecodeError):
                return {}

    async def _llm_lab_correlation(
        self,
        lab_data: List[Dict],
        abnormal_labs: List[Dict],
        patient_context: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Use LLM to correlate lab results with clinical picture."""
        system_prompt = """You are a clinical laboratory medicine specialist AI. Analyze lab results
in the context of the patient's symptoms, conditions, medications, and demographics.

For abnormal results, identify:
1. Clinical significance
2. Possible underlying conditions (with ICD-10 codes)
3. Whether abnormalities may be medication-related
4. Recommended follow-up testing
5. Urgency of follow-up

Respond ONLY in valid JSON:
{
    "correlations": [{"lab_test": "string", "finding": "string", "clinical_significance": "string", "related_icd10": "string"}],
    "possible_conditions": [{"icd10_code": "string", "condition": "string", "supporting_labs": ["string"], "confidence": 0.0-1.0}],
    "follow_up_tests": [{"test": "string", "rationale": "string", "urgency": "routine|urgent|stat"}],
    "clinical_significance": "string — overall assessment summary"
}"""

        user_prompt = f"""PATIENT CONTEXT:
{json.dumps(patient_context, indent=2, default=str)}

ALL RECENT LAB RESULTS:
{json.dumps(lab_data, indent=2, default=str)}

ABNORMAL RESULTS:
{json.dumps(abnormal_labs, indent=2, default=str)}

Correlate these lab results with the patient's clinical picture."""

        raw = await self._call_llm([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ])

        if not raw:
            return {}

        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            try:
                start = raw.index("{")
                end = raw.rindex("}") + 1
                return json.loads(raw[start:end])
            except (ValueError, json.JSONDecodeError):
                return {}

    # ── Helpers ────────────────────────────────────────────────────

    def _get_chapter_title(self, chapter: str) -> str:
        from app.services.icd10_catalog import ICD10_CHAPTERS
        ch = ICD10_CHAPTERS.get(chapter, {})
        return ch.get("title", "Unknown chapter")
