"""Generic clinical report builder — one spec, two renderers.

A report is described once as a `ReportSpec` and rendered either as a PDF or as
plain text. That matters because the clients show a text preview and download a
PDF: with two independent renderers those drift, and the document a clinician
receives stops matching what the patient saw on screen.

Nothing here knows about dialysis, labs, or any particular screen. Callers build
a spec; this module lays it out.
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from datetime import datetime
from typing import Callable, Sequence

_BRAND = "#1a3c5e"
_ACCENT = "#2d6a9f"
_RULE = "#c8daea"
_ZEBRA = "#f7fbff"
_HEAD_BG = "#eaf2fb"
_DANGER = "#b91c1c"

_TEXT_WIDTH = 78


@dataclass
class KeyValueSection:
    """Label/value pairs — patient details, session summary."""

    heading: str | None = None
    rows: Sequence[tuple[str, str]] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not self.rows


@dataclass
class TableSection:
    """A real table. `highlight` marks a row for emphasis (e.g. out of range)."""

    heading: str | None = None
    columns: Sequence[str] = field(default_factory=list)
    rows: Sequence[Sequence[str]] = field(default_factory=list)
    highlight: Callable[[Sequence[str]], bool] | None = None
    #: Relative column widths; equal when omitted.
    widths: Sequence[float] | None = None

    @property
    def is_empty(self) -> bool:
        return not self.rows


@dataclass
class TextSection:
    heading: str | None = None
    body: str = ""

    @property
    def is_empty(self) -> bool:
        return not (self.body or "").strip()


Section = KeyValueSection | TableSection | TextSection


@dataclass
class ReportSpec:
    title: str
    subtitle: str | None = None
    #: Small label/value pairs printed under the title (patient, date range).
    meta: Sequence[tuple[str, str]] = field(default_factory=list)
    sections: Sequence[Section] = field(default_factory=list)
    footer: str = "Generated by ALAFIA Health Platform — Confidential Medical Record"
    generated_at: datetime | None = None

    @property
    def stamp(self) -> str:
        moment = self.generated_at or datetime.now()
        return moment.strftime("%B %d, %Y %I:%M %p")

    def visible_sections(self) -> list[Section]:
        """Empty sections are dropped — a blank heading reads as missing data."""
        return [s for s in self.sections if not s.is_empty]


# ── Plain text ───────────────────────────────────────────────────────────────

def render_text(spec: ReportSpec) -> str:
    lines: list[str] = [spec.title, "=" * min(len(spec.title), _TEXT_WIDTH)]
    if spec.subtitle:
        lines.append(spec.subtitle)
    lines.append(f"Generated: {spec.stamp}")

    for label, value in spec.meta:
        lines.append(f"{label}: {value}")
    lines.append("")

    for section in spec.visible_sections():
        if isinstance(section, KeyValueSection):
            if section.heading:
                lines += [section.heading, "-" * min(len(section.heading), _TEXT_WIDTH)]
            width = max((len(k) for k, _ in section.rows if k), default=0)
            for key, value in section.rows:
                lines.append(f"  {key.ljust(width)}  {value}" if key else f"  {value}")

        elif isinstance(section, TableSection):
            if section.heading:
                lines += [section.heading, "-" * min(len(section.heading), _TEXT_WIDTH)]
            lines += _text_table(section)

        elif isinstance(section, TextSection):
            if section.heading:
                lines += [section.heading, "-" * min(len(section.heading), _TEXT_WIDTH)]
            lines += [f"  {line}" for line in section.body.splitlines()]

        lines.append("")

    lines.append("-" * _TEXT_WIDTH)
    lines.append(spec.footer)
    return "\n".join(lines)


def _text_table(section: TableSection) -> list[str]:
    columns = [str(c) for c in section.columns]
    body = [[("" if cell is None else str(cell)) for cell in row] for row in section.rows]

    widths = [len(c) for c in columns]
    for row in body:
        for index, cell in enumerate(row):
            if index < len(widths):
                widths[index] = max(widths[index], len(cell))

    out = ["  " + "  ".join(c.ljust(widths[i]) for i, c in enumerate(columns))]
    out.append("  " + "  ".join("-" * w for w in widths))
    for original, row in zip(section.rows, body):
        marker = "*" if section.highlight and section.highlight(original) else " "
        out.append(
            f"{marker} " + "  ".join(
                cell.ljust(widths[i]) if i < len(widths) else cell
                for i, cell in enumerate(row)
            )
        )
    if section.highlight and any(section.highlight(r) for r in section.rows):
        out.append("  (* marked rows need attention)")
    return out


# ── PDF ──────────────────────────────────────────────────────────────────────

def render_pdf(spec: ReportSpec) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        title=spec.title,
    )

    styles = getSampleStyleSheet()
    normal = styles["Normal"]
    title_style = ParagraphStyle(
        "DocTitle", parent=styles["Title"], fontSize=16,
        textColor=colors.HexColor(_BRAND), spaceAfter=4,
    )
    sub_style = ParagraphStyle("DocSub", parent=normal, fontSize=9, textColor=colors.grey)
    head_style = ParagraphStyle(
        "SectionHead", parent=styles["Heading2"], fontSize=11,
        textColor=colors.HexColor(_ACCENT), spaceBefore=12, spaceAfter=4,
    )
    cell = ParagraphStyle("Cell", parent=normal, fontSize=8.5, leading=11)
    cell_bold = ParagraphStyle("CellBold", parent=cell, fontName="Helvetica-Bold")
    danger = ParagraphStyle("CellDanger", parent=cell, textColor=colors.HexColor(_DANGER))

    story = [Paragraph(spec.title, title_style)]
    if spec.subtitle:
        story.append(Paragraph(spec.subtitle, sub_style))
    story.append(Paragraph(f"Generated: {spec.stamp}", sub_style))
    for label, value in spec.meta:
        story.append(Paragraph(f"<b>{label}:</b> {value}", sub_style))
    story.append(HRFlowable(width="100%", thickness=1,
                            color=colors.HexColor(_ACCENT), spaceBefore=6, spaceAfter=10))

    usable = doc.width

    for section in spec.visible_sections():
        if section.heading:
            story.append(Paragraph(section.heading, head_style))

        if isinstance(section, KeyValueSection):
            data = [[Paragraph(f"<b>{k}</b>", cell), Paragraph(str(v), cell)]
                    for k, v in section.rows]
            table = Table(data, colWidths=[usable * 0.32, usable * 0.68])
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor(_HEAD_BG)),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor(_RULE)),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor(_ZEBRA)]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(table)

        elif isinstance(section, TableSection):
            header = [Paragraph(f"<b>{c}</b>", cell_bold) for c in section.columns]
            data = [header]
            flagged: list[int] = []
            for index, row in enumerate(section.rows, start=1):
                is_flagged = bool(section.highlight and section.highlight(row))
                if is_flagged:
                    flagged.append(index)
                style = danger if is_flagged else cell
                data.append([
                    Paragraph("" if c is None else str(c), style) for c in row
                ])

            weights = list(section.widths or [1] * len(section.columns))
            total = sum(weights) or 1
            widths = [usable * (w / total) for w in weights]

            table = Table(data, colWidths=widths, repeatRows=1)
            style_commands = [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(_HEAD_BG)),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor(_RULE)),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor(_ZEBRA)]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ]
            for index in flagged:
                style_commands.append(
                    ("BACKGROUND", (0, index), (-1, index), colors.HexColor("#fee2e2"))
                )
            table.setStyle(TableStyle(style_commands))
            story.append(table)

        elif isinstance(section, TextSection):
            for paragraph in section.body.split("\n\n"):
                story.append(Paragraph(paragraph.replace("\n", "<br/>"), normal))
                story.append(Spacer(1, 4))

        story.append(Spacer(1, 8))

    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        spec.footer,
        ParagraphStyle("Footer", parent=normal, fontSize=8, textColor=colors.grey),
    ))

    doc.build(story)
    return buffer.getvalue()
