"""add_pd_directives_sharing_wellness

Revision ID: 2940057c9079
Revises: a3b4c5d6e7f8
Create Date: 2026-02-16 08:42:14.348409
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '2940057c9079'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_directives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_agent_name', sa.String(length=255), nullable=True),
    sa.Column('primary_agent_relationship', sa.String(length=100), nullable=True),
    sa.Column('primary_agent_phone', sa.String(length=50), nullable=True),
    sa.Column('primary_agent_email', sa.String(length=255), nullable=True),
    sa.Column('primary_agent_address', sa.Text(), nullable=True),
    sa.Column('alternate_agent_name', sa.String(length=255), nullable=True),
    sa.Column('alternate_agent_relationship', sa.String(length=100), nullable=True),
    sa.Column('alternate_agent_phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_agent_email', sa.String(length=255), nullable=True),
    sa.Column('alternate_agent_address', sa.Text(), nullable=True),
    sa.Column('organ_donation_preference', sa.String(length=50), nullable=True),
    sa.Column('specific_organs_to_donate', sa.Text(), nullable=True),
    sa.Column('specific_organs_not_to_donate', sa.Text(), nullable=True),
    sa.Column('life_support_preference', sa.String(length=100), nullable=True),
    sa.Column('cpr_preference', sa.String(length=50), nullable=True),
    sa.Column('ventilator_preference', sa.String(length=50), nullable=True),
    sa.Column('feeding_tube_preference', sa.String(length=50), nullable=True),
    sa.Column('dialysis_preference', sa.String(length=50), nullable=True),
    sa.Column('blood_transfusion_preference', sa.String(length=50), nullable=True),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.Column('document_signed', sa.Boolean(), nullable=True),
    sa.Column('document_date', sa.String(length=20), nullable=True),
    sa.Column('witness_name', sa.String(length=255), nullable=True),
    sa.Column('notarized', sa.Boolean(), nullable=True),
    sa.Column('document_location', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advanced_directives_id'), 'advanced_directives', ['id'], unique=False)
    op.create_index(op.f('ix_advanced_directives_user_id'), 'advanced_directives', ['user_id'], unique=True)
    op.create_table('data_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('grantee_user_id', sa.Integer(), nullable=True),
    sa.Column('grantee_email', sa.String(length=255), nullable=True),
    sa.Column('grantee_display_name', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('read_access', sa.Boolean(), nullable=False),
    sa.Column('write_access', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_grants_grantee_user_id'), 'data_grants', ['grantee_user_id'], unique=False)
    op.create_index(op.f('ix_data_grants_id'), 'data_grants', ['id'], unique=False)
    op.create_index(op.f('ix_data_grants_owner_id'), 'data_grants', ['owner_id'], unique=False)
    op.create_table('data_share_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('data_types', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_share_invitations_id'), 'data_share_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_data_share_invitations_sender_id'), 'data_share_invitations', ['sender_id'], unique=False)
    op.create_table('exercise_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('fitness_level', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('plan_data', sa.Text(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('weekly_minutes_target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_plans_id'), 'exercise_plans', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_plans_user_id'), 'exercise_plans', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('dietary_pattern', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('plan_data', sa.Text(), nullable=False),
    sa.Column('shopping_list', sa.Text(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('total_daily_calories', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('wellness_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('nutrition_score', sa.Float(), nullable=True),
    sa.Column('fitness_score', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('mood_score', sa.Float(), nullable=True),
    sa.Column('vitals_score', sa.Float(), nullable=True),
    sa.Column('medication_adherence_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_scores_id'), 'wellness_scores', ['id'], unique=False)
    op.create_index(op.f('ix_wellness_scores_user_id'), 'wellness_scores', ['user_id'], unique=False)
    op.create_table('pd_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('modality', sa.String(length=10), nullable=False),
    sa.Column('pre_weight_kg', sa.Float(), nullable=True),
    sa.Column('post_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_uf_ml', sa.Float(), nullable=True),
    sa.Column('total_uf_ml', sa.Float(), nullable=True),
    sa.Column('pre_bp_systolic', sa.Integer(), nullable=True),
    sa.Column('pre_bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('post_bp_systolic', sa.Integer(), nullable=True),
    sa.Column('post_bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('pre_temp_f', sa.Float(), nullable=True),
    sa.Column('post_temp_f', sa.Float(), nullable=True),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('total_volume_ml', sa.Float(), nullable=True),
    sa.Column('fill_volume_ml', sa.Float(), nullable=True),
    sa.Column('number_of_cycles', sa.Integer(), nullable=True),
    sa.Column('therapy_time_hours', sa.Float(), nullable=True),
    sa.Column('last_fill_volume_ml', sa.Float(), nullable=True),
    sa.Column('exit_site_status', sa.String(length=50), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['chronic_conditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pd_sessions_id'), 'pd_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_pd_sessions_user_id'), 'pd_sessions', ['user_id'], unique=False)
    op.create_table('pd_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exchange_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('drain_start', sa.String(length=10), nullable=True),
    sa.Column('drain_end', sa.String(length=10), nullable=True),
    sa.Column('fill_end', sa.String(length=10), nullable=True),
    sa.Column('solution_type', sa.String(length=100), nullable=True),
    sa.Column('inflow_volume_ml', sa.Float(), nullable=True),
    sa.Column('outflow_volume_ml', sa.Float(), nullable=True),
    sa.Column('uf_ml', sa.Float(), nullable=True),
    sa.Column('dwell_time_minutes', sa.Integer(), nullable=True),
    sa.Column('effluent_clarity', sa.String(length=20), nullable=True),
    sa.Column('effluent_color', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pd_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pd_exchanges_id'), 'pd_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_pd_exchanges_session_id'), 'pd_exchanges', ['session_id'], unique=False)
    op.execute("DROP INDEX IF EXISTS idx_medication_logs_user_date")
    op.execute("DROP TABLE IF EXISTS medication_logs")
    op.alter_column('block_records', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('block_records', 'action',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('block_records', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('block_records', 'previous_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('block_records', 'hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('block_records', 'nonce',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('block_records', 'entity_type',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('block_records', 'merkle_root',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('block_records', 'signature',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('block_records', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('block_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_block_records_actor_chain', table_name='block_records')
    op.drop_index('ix_block_records_chain_index', table_name='block_records')
    op.drop_index('ix_block_records_entity', table_name='block_records')
    op.create_index('ix_block_actor_chain', 'block_records', ['actor_id', 'chain_type'], unique=False)
    op.create_index('ix_block_chain_index', 'block_records', ['chain_type', 'index'], unique=False)
    op.create_index('ix_block_entity', 'block_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_block_records_id'), 'block_records', ['id'], unique=False)
    op.alter_column('calendar_events', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('calendar_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.alter_column('chain_meta', 'genesis_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('chain_meta', 'latest_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('chain_meta', 'merkle_root',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('chain_meta', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chain_meta', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chain_meta_id'), 'chain_meta', ['id'], unique=False)
    op.alter_column('diagnostic_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnostic_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_diagnostic_assessments_id'), 'diagnostic_assessments', ['id'], unique=False)
    op.alter_column('differential_diagnoses', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('differential_diagnoses', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('differential_diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_differential_diagnoses_id'), 'differential_diagnoses', ['id'], unique=False)
    op.alter_column('health_sync_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('health_sync_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_sync_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_health_sync_connections_id'), 'health_sync_connections', ['id'], unique=False)
    op.create_index(op.f('ix_intradialytic_readings_id'), 'intradialytic_readings', ['id'], unique=False)
    op.alter_column('lab_correlation_reports', 'labs_analyzed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('lab_correlation_reports', 'abnormal_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('lab_correlation_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_lab_correlation_reports_id'), 'lab_correlation_reports', ['id'], unique=False)
    op.alter_column('physician_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('physician_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_physician_reviews_id'), 'physician_reviews', ['id'], unique=False)
    op.alter_column('physicians', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('physicians', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_physicians_id'), 'physicians', ['id'], unique=False)
    op.alter_column('provider_availability', 'slot_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('provider_availability', 'max_patients_per_slot',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('provider_availability', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('provider_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_provider_availability_id'), 'provider_availability', ['id'], unique=False)
    op.alter_column('saved_physicians', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_saved_physicians_id'), 'saved_physicians', ['id'], unique=False)
    op.alter_column('screening_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('screening_recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_screening_recommendations_id'), 'screening_recommendations', ['id'], unique=False)
    op.alter_column('session_notes', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('session_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_session_notes_id'), 'session_notes', ['id'], unique=False)
    op.alter_column('session_participants', 'camera_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('session_participants', 'microphone_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('session_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_session_participants_id'), 'session_participants', ['id'], unique=False)
    op.alter_column('session_recordings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_session_recordings_id'), 'session_recordings', ['id'], unique=False)
    op.alter_column('session_signals', 'is_consumed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('session_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_session_signals_id'), 'session_signals', ['id'], unique=False)
    op.alter_column('session_transcripts', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('session_transcripts', 'is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('session_transcripts', 'is_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('session_transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_session_transcripts_id'), 'session_transcripts', ['id'], unique=False)
    op.alter_column('synced_records', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_synced_records_id'), 'synced_records', ['id'], unique=False)
    op.alter_column('telehealth_sessions', 'session_code',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID-style room code for joining',
               existing_nullable=False)
    op.alter_column('telehealth_sessions', 'recording_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telehealth_sessions', 'transcription_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'screen_sharing_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'chat_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'waiting_room_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'follow_up_needed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telehealth_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('telehealth_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_telehealth_sessions_id'), 'telehealth_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telehealth_sessions_id'), table_name='telehealth_sessions')
    op.alter_column('telehealth_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telehealth_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telehealth_sessions', 'follow_up_needed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('telehealth_sessions', 'waiting_room_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'chat_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'screen_sharing_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'transcription_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telehealth_sessions', 'recording_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('telehealth_sessions', 'session_code',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID-style room code for joining',
               existing_nullable=False)
    op.drop_index(op.f('ix_synced_records_id'), table_name='synced_records')
    op.alter_column('synced_records', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_session_transcripts_id'), table_name='session_transcripts')
    op.alter_column('session_transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_transcripts', 'is_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('session_transcripts', 'is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('session_transcripts', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_index(op.f('ix_session_signals_id'), table_name='session_signals')
    op.alter_column('session_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_signals', 'is_consumed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_session_recordings_id'), table_name='session_recordings')
    op.alter_column('session_recordings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_session_participants_id'), table_name='session_participants')
    op.alter_column('session_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_participants', 'microphone_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('session_participants', 'camera_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_session_notes_id'), table_name='session_notes')
    op.alter_column('session_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_notes', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_screening_recommendations_id'), table_name='screening_recommendations')
    op.alter_column('screening_recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('screening_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_saved_physicians_id'), table_name='saved_physicians')
    op.alter_column('saved_physicians', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_provider_availability_id'), table_name='provider_availability')
    op.alter_column('provider_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('provider_availability', 'max_patients_per_slot',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('provider_availability', 'slot_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.drop_index(op.f('ix_physicians_id'), table_name='physicians')
    op.alter_column('physicians', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('physicians', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_physician_reviews_id'), table_name='physician_reviews')
    op.alter_column('physician_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('physician_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lab_correlation_reports_id'), table_name='lab_correlation_reports')
    op.alter_column('lab_correlation_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lab_correlation_reports', 'abnormal_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('lab_correlation_reports', 'labs_analyzed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_intradialytic_readings_id'), table_name='intradialytic_readings')
    op.drop_index(op.f('ix_health_sync_connections_id'), table_name='health_sync_connections')
    op.alter_column('health_sync_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_sync_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_sync_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_differential_diagnoses_id'), table_name='differential_diagnoses')
    op.alter_column('differential_diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('differential_diagnoses', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('differential_diagnoses', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_diagnostic_assessments_id'), table_name='diagnostic_assessments')
    op.alter_column('diagnostic_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnostic_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chain_meta_id'), table_name='chain_meta')
    op.alter_column('chain_meta', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chain_meta', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chain_meta', 'merkle_root',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('chain_meta', 'latest_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('chain_meta', 'genesis_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.alter_column('calendar_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('calendar_events', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_block_records_id'), table_name='block_records')
    op.drop_index('ix_block_entity', table_name='block_records')
    op.drop_index('ix_block_chain_index', table_name='block_records')
    op.drop_index('ix_block_actor_chain', table_name='block_records')
    op.create_index('ix_block_records_entity', 'block_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_block_records_chain_index', 'block_records', ['chain_type', 'index'], unique=False)
    op.create_index('ix_block_records_actor_chain', 'block_records', ['actor_id', 'chain_type'], unique=False)
    op.alter_column('block_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('block_records', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('block_records', 'signature',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('block_records', 'merkle_root',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('block_records', 'entity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('block_records', 'nonce',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('block_records', 'hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('block_records', 'previous_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('block_records', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('block_records', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('block_records', 'timestamp',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('log_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('medication_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pre_systolic_bp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pre_diastolic_bp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pre_heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_systolic_bp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_diastolic_bp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='medication_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='medication_logs_pkey')
    )
    op.create_index('idx_medication_logs_user_date', 'medication_logs', ['user_id', 'log_date'], unique=False)
    op.drop_index(op.f('ix_pd_exchanges_session_id'), table_name='pd_exchanges')
    op.drop_index(op.f('ix_pd_exchanges_id'), table_name='pd_exchanges')
    op.drop_table('pd_exchanges')
    op.drop_index(op.f('ix_pd_sessions_user_id'), table_name='pd_sessions')
    op.drop_index(op.f('ix_pd_sessions_id'), table_name='pd_sessions')
    op.drop_table('pd_sessions')
    op.drop_index(op.f('ix_wellness_scores_user_id'), table_name='wellness_scores')
    op.drop_index(op.f('ix_wellness_scores_id'), table_name='wellness_scores')
    op.drop_table('wellness_scores')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_exercise_plans_user_id'), table_name='exercise_plans')
    op.drop_index(op.f('ix_exercise_plans_id'), table_name='exercise_plans')
    op.drop_table('exercise_plans')
    op.drop_index(op.f('ix_data_share_invitations_sender_id'), table_name='data_share_invitations')
    op.drop_index(op.f('ix_data_share_invitations_id'), table_name='data_share_invitations')
    op.drop_table('data_share_invitations')
    op.drop_index(op.f('ix_data_grants_owner_id'), table_name='data_grants')
    op.drop_index(op.f('ix_data_grants_id'), table_name='data_grants')
    op.drop_index(op.f('ix_data_grants_grantee_user_id'), table_name='data_grants')
    op.drop_table('data_grants')
    op.drop_index(op.f('ix_advanced_directives_user_id'), table_name='advanced_directives')
    op.drop_index(op.f('ix_advanced_directives_id'), table_name='advanced_directives')
    op.drop_table('advanced_directives')
    # ### end Alembic commands ###
