"""Add AI memory and learning intelligence

Revision ID: 3e5633413cb9
Revises: 7c1bfa760608
Create Date: 2026-02-14 03:50:14.867294
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3e5633413cb9'
down_revision: Union[str, None] = '7c1bfa760608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collective_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('pattern_name', sa.String(length=200), nullable=False),
    sa.Column('pattern_description', sa.Text(), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('applicable_demographics', sa.JSON(), nullable=True),
    sa.Column('applicable_conditions', sa.JSON(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('positive_feedback_count', sa.Integer(), nullable=False),
    sa.Column('negative_feedback_count', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_active', 'collective_insights', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_collective_insights_category'), 'collective_insights', ['category'], unique=False)
    op.create_index(op.f('ix_collective_insights_discovered_at'), 'collective_insights', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_collective_insights_id'), 'collective_insights', ['id'], unique=False)
    op.create_index(op.f('ix_collective_insights_is_active'), 'collective_insights', ['is_active'], unique=False)
    op.create_index(op.f('ix_collective_insights_pattern_type'), 'collective_insights', ['pattern_type'], unique=False)
    op.create_table('global_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('source_organization', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('evidence_level', sa.String(length=20), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applies_to_demographics', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('times_referenced', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_topic_active', 'global_knowledge', ['domain', 'topic', 'is_active'], unique=False)
    op.create_index(op.f('ix_global_knowledge_created_at'), 'global_knowledge', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_knowledge_domain'), 'global_knowledge', ['domain'], unique=False)
    op.create_index(op.f('ix_global_knowledge_id'), 'global_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_global_knowledge_is_active'), 'global_knowledge', ['is_active'], unique=False)
    op.create_index(op.f('ix_global_knowledge_knowledge_type'), 'global_knowledge', ['knowledge_type'], unique=False)
    op.create_index(op.f('ix_global_knowledge_topic'), 'global_knowledge', ['topic'], unique=False)
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('context_used', sa.JSON(), nullable=False),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('was_followed', sa.Boolean(), nullable=True),
    sa.Column('outcome_measured', sa.JSON(), nullable=True),
    sa.Column('user_sentiment', sa.String(length=20), nullable=True),
    sa.Column('recommendation_quality_score', sa.Float(), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feedback_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type_category', 'ai_interactions', ['interaction_type', 'category'], unique=False)
    op.create_index('idx_user_created', 'ai_interactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_interactions_created_at'), 'ai_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_interactions_id'), 'ai_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_interaction_type'), 'ai_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_ai_interactions_user_id'), 'ai_interactions', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('insight_key', sa.String(length=100), nullable=False),
    sa.Column('insight_value', sa.Text(), nullable=False),
    sa.Column('insight_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('learned_from_period', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_category_key', 'user_memories', ['user_id', 'category', 'insight_key'], unique=False)
    op.create_index(op.f('ix_user_memories_category'), 'user_memories', ['category'], unique=False)
    op.create_index(op.f('ix_user_memories_created_at'), 'user_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_memories_id'), 'user_memories', ['id'], unique=False)
    op.create_index(op.f('ix_user_memories_insight_key'), 'user_memories', ['insight_key'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('intelligence_level', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('memory_id', sa.Integer(), nullable=True),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('confidence_change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['collective_insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['global_knowledge.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memory_id'], ['user_memories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_created_at'), 'learning_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_id'), 'learning_events', ['id'], unique=False)
    op.create_index(op.f('ix_learning_events_intelligence_level'), 'learning_events', ['intelligence_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_events_intelligence_level'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_created_at'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_insight_key'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_created_at'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_category'), table_name='user_memories')
    op.drop_index('idx_user_category_key', table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_ai_interactions_user_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_interaction_type'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_created_at'), table_name='ai_interactions')
    op.drop_index('idx_user_created', table_name='ai_interactions')
    op.drop_index('idx_type_category', table_name='ai_interactions')
    op.drop_table('ai_interactions')
    op.drop_index(op.f('ix_global_knowledge_topic'), table_name='global_knowledge')
    op.drop_index(op.f('ix_global_knowledge_knowledge_type'), table_name='global_knowledge')
    op.drop_index(op.f('ix_global_knowledge_is_active'), table_name='global_knowledge')
    op.drop_index(op.f('ix_global_knowledge_id'), table_name='global_knowledge')
    op.drop_index(op.f('ix_global_knowledge_domain'), table_name='global_knowledge')
    op.drop_index(op.f('ix_global_knowledge_created_at'), table_name='global_knowledge')
    op.drop_index('idx_domain_topic_active', table_name='global_knowledge')
    op.drop_table('global_knowledge')
    op.drop_index(op.f('ix_collective_insights_pattern_type'), table_name='collective_insights')
    op.drop_index(op.f('ix_collective_insights_is_active'), table_name='collective_insights')
    op.drop_index(op.f('ix_collective_insights_id'), table_name='collective_insights')
    op.drop_index(op.f('ix_collective_insights_discovered_at'), table_name='collective_insights')
    op.drop_index(op.f('ix_collective_insights_category'), table_name='collective_insights')
    op.drop_index('idx_category_active', table_name='collective_insights')
    op.drop_table('collective_insights')
    # ### end Alembic commands ###
