"""Add comprehensive health tracking models

Revision ID: 6cd11de19201
Revises: 4bd2ef8ca06d
Create Date: 2026-02-14 03:28:11.171220
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6cd11de19201'
down_revision: Union[str, None] = '4bd2ef8ca06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bowel_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_time', sa.Time(), nullable=True),
    sa.Column('bristol_scale', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('consistency', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('blood_present', sa.Boolean(), nullable=True),
    sa.Column('mucus_present', sa.Boolean(), nullable=True),
    sa.Column('undigested_food', sa.Boolean(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('straining', sa.Boolean(), nullable=True),
    sa.Column('urgency', sa.Boolean(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('associated_symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bowel_movements_id'), 'bowel_movements', ['id'], unique=False)
    op.create_index(op.f('ix_bowel_movements_user_id'), 'bowel_movements', ['user_id'], unique=False)
    op.create_table('health_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('snomed_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('diagnosed_by', sa.String(length=255), nullable=True),
    sa.Column('healthcare_facility', sa.String(length=255), nullable=True),
    sa.Column('current_treatment', sa.Text(), nullable=True),
    sa.Column('treatment_response', sa.Text(), nullable=True),
    sa.Column('affects_daily_life', sa.Boolean(), nullable=True),
    sa.Column('requires_accommodation', sa.Boolean(), nullable=True),
    sa.Column('hereditary', sa.Boolean(), nullable=True),
    sa.Column('related_conditions', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_conditions_id'), 'health_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_health_conditions_user_id'), 'health_conditions', ['user_id'], unique=False)
    op.create_table('illness_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('illness_name', sa.String(length=255), nullable=False),
    sa.Column('illness_type', sa.String(length=100), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('recovery_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('contagious', sa.Boolean(), nullable=True),
    sa.Column('primary_symptoms', sa.Text(), nullable=True),
    sa.Column('secondary_symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosed_by', sa.String(length=255), nullable=True),
    sa.Column('hospitalized', sa.Boolean(), nullable=True),
    sa.Column('days_hospitalized', sa.Integer(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('medications_prescribed', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('suspected_source', sa.Text(), nullable=True),
    sa.Column('exposure_date', sa.Date(), nullable=True),
    sa.Column('days_missed_work', sa.Integer(), nullable=True),
    sa.Column('days_bedridden', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_illness_logs_id'), 'illness_logs', ['id'], unique=False)
    op.create_index(op.f('ix_illness_logs_user_id'), 'illness_logs', ['user_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.Time(), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_hours', sa.Float(), nullable=True),
    sa.Column('light_sleep_hours', sa.Float(), nullable=True),
    sa.Column('rem_sleep_hours', sa.Float(), nullable=True),
    sa.Column('awake_hours', sa.Float(), nullable=True),
    sa.Column('times_awakened', sa.Integer(), nullable=True),
    sa.Column('time_to_fall_asleep_min', sa.Integer(), nullable=True),
    sa.Column('sleep_environment', sa.String(length=100), nullable=True),
    sa.Column('room_temperature_c', sa.Float(), nullable=True),
    sa.Column('noise_level', sa.String(length=20), nullable=True),
    sa.Column('caffeine_cutoff_hours', sa.Float(), nullable=True),
    sa.Column('alcohol_consumed', sa.Boolean(), nullable=True),
    sa.Column('exercise_hours_before', sa.Float(), nullable=True),
    sa.Column('screen_time_before_min', sa.Integer(), nullable=True),
    sa.Column('sleep_aids', sa.Text(), nullable=True),
    sa.Column('had_dreams', sa.Boolean(), nullable=True),
    sa.Column('had_nightmares', sa.Boolean(), nullable=True),
    sa.Column('sleep_disorders', sa.Text(), nullable=True),
    sa.Column('morning_alertness', sa.Integer(), nullable=True),
    sa.Column('morning_mood', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_id'), 'sleep_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    op.create_table('urination_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_time', sa.Time(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('clarity', sa.String(length=50), nullable=True),
    sa.Column('odor', sa.String(length=50), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('stream_strength', sa.String(length=20), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('burning_sensation', sa.Boolean(), nullable=True),
    sa.Column('urgency', sa.Boolean(), nullable=True),
    sa.Column('frequency_increased', sa.Boolean(), nullable=True),
    sa.Column('blood_present', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('nighttime', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urination_logs_id'), 'urination_logs', ['id'], unique=False)
    op.create_index(op.f('ix_urination_logs_user_id'), 'urination_logs', ['user_id'], unique=False)
    op.create_table('vitals_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_time', sa.Time(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_position', sa.String(length=50), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('heart_rhythm', sa.String(length=50), nullable=True),
    sa.Column('body_temperature_c', sa.Float(), nullable=True),
    sa.Column('temperature_location', sa.String(length=50), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('blood_oxygen_pct', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('bone_mass_kg', sa.Float(), nullable=True),
    sa.Column('water_pct', sa.Float(), nullable=True),
    sa.Column('visceral_fat', sa.Integer(), nullable=True),
    sa.Column('waist_circumference_cm', sa.Float(), nullable=True),
    sa.Column('hip_circumference_cm', sa.Float(), nullable=True),
    sa.Column('neck_circumference_cm', sa.Float(), nullable=True),
    sa.Column('chest_circumference_cm', sa.Float(), nullable=True),
    sa.Column('blood_glucose_mg_dl', sa.Float(), nullable=True),
    sa.Column('glucose_timing', sa.String(length=50), nullable=True),
    sa.Column('peak_flow', sa.Float(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('measurement_device', sa.String(length=100), nullable=True),
    sa.Column('measurement_location', sa.String(length=100), nullable=True),
    sa.Column('measured_by', sa.String(length=100), nullable=True),
    sa.Column('fasting', sa.Boolean(), nullable=True),
    sa.Column('after_exercise', sa.Boolean(), nullable=True),
    sa.Column('after_medication', sa.Boolean(), nullable=True),
    sa.Column('stressed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitals_logs_id'), 'vitals_logs', ['id'], unique=False)
    op.create_index(op.f('ix_vitals_logs_user_id'), 'vitals_logs', ['user_id'], unique=False)
    op.create_table('vomiting_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_time', sa.Time(), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('consistency', sa.String(length=50), nullable=True),
    sa.Column('contains_food', sa.Boolean(), nullable=True),
    sa.Column('contains_bile', sa.Boolean(), nullable=True),
    sa.Column('contains_blood', sa.Boolean(), nullable=True),
    sa.Column('nausea_before', sa.Boolean(), nullable=True),
    sa.Column('nausea_after', sa.Boolean(), nullable=True),
    sa.Column('projectile', sa.Boolean(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('time_since_last_meal_hours', sa.Float(), nullable=True),
    sa.Column('relief_after', sa.Boolean(), nullable=True),
    sa.Column('fever', sa.Boolean(), nullable=True),
    sa.Column('diarrhea', sa.Boolean(), nullable=True),
    sa.Column('headache', sa.Boolean(), nullable=True),
    sa.Column('dizziness', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vomiting_logs_id'), 'vomiting_logs', ['id'], unique=False)
    op.create_index(op.f('ix_vomiting_logs_user_id'), 'vomiting_logs', ['user_id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('symptom_name', sa.String(length=255), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('location_specific', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('symptom_type', sa.String(length=100), nullable=True),
    sa.Column('quality', sa.String(length=100), nullable=True),
    sa.Column('onset', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('triggers', sa.Text(), nullable=True),
    sa.Column('relievers', sa.Text(), nullable=True),
    sa.Column('aggravating_factors', sa.Text(), nullable=True),
    sa.Column('affects_function', sa.Boolean(), nullable=True),
    sa.Column('interferes_sleep', sa.Boolean(), nullable=True),
    sa.Column('interferes_work', sa.Boolean(), nullable=True),
    sa.Column('interferes_activities', sa.Boolean(), nullable=True),
    sa.Column('self_treatment', sa.Text(), nullable=True),
    sa.Column('medications_taken', sa.Text(), nullable=True),
    sa.Column('treatment_effective', sa.Boolean(), nullable=True),
    sa.Column('sought_medical_care', sa.Boolean(), nullable=True),
    sa.Column('emergency_visit', sa.Boolean(), nullable=True),
    sa.Column('other_symptoms', sa.Text(), nullable=True),
    sa.Column('related_condition_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_condition_id'], ['health_conditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_id'), 'symptom_logs', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.add_column('nutrition_logs', sa.Column('saturated_fat_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('trans_fat_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('monounsaturated_fat_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('polyunsaturated_fat_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('omega3_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('omega6_g', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('cholesterol_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('potassium_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('calcium_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('iron_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('magnesium_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('zinc_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('phosphorus_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('copper_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('manganese_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('selenium_mcg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('iodine_mcg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_a_iu', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_c_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_d_iu', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_e_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_k_mcg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b1_thiamine_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b2_riboflavin_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b3_niacin_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b5_pantothenic_acid_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b6_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b7_biotin_mcg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b9_folate_mcg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('vitamin_b12_mcg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('choline_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('caffeine_mg', sa.Float(), nullable=True))
    op.add_column('nutrition_logs', sa.Column('alcohol_g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_logs', 'alcohol_g')
    op.drop_column('nutrition_logs', 'caffeine_mg')
    op.drop_column('nutrition_logs', 'choline_mg')
    op.drop_column('nutrition_logs', 'vitamin_b12_mcg')
    op.drop_column('nutrition_logs', 'vitamin_b9_folate_mcg')
    op.drop_column('nutrition_logs', 'vitamin_b7_biotin_mcg')
    op.drop_column('nutrition_logs', 'vitamin_b6_mg')
    op.drop_column('nutrition_logs', 'vitamin_b5_pantothenic_acid_mg')
    op.drop_column('nutrition_logs', 'vitamin_b3_niacin_mg')
    op.drop_column('nutrition_logs', 'vitamin_b2_riboflavin_mg')
    op.drop_column('nutrition_logs', 'vitamin_b1_thiamine_mg')
    op.drop_column('nutrition_logs', 'vitamin_k_mcg')
    op.drop_column('nutrition_logs', 'vitamin_e_mg')
    op.drop_column('nutrition_logs', 'vitamin_d_iu')
    op.drop_column('nutrition_logs', 'vitamin_c_mg')
    op.drop_column('nutrition_logs', 'vitamin_a_iu')
    op.drop_column('nutrition_logs', 'iodine_mcg')
    op.drop_column('nutrition_logs', 'selenium_mcg')
    op.drop_column('nutrition_logs', 'manganese_mg')
    op.drop_column('nutrition_logs', 'copper_mg')
    op.drop_column('nutrition_logs', 'phosphorus_mg')
    op.drop_column('nutrition_logs', 'zinc_mg')
    op.drop_column('nutrition_logs', 'magnesium_mg')
    op.drop_column('nutrition_logs', 'iron_mg')
    op.drop_column('nutrition_logs', 'calcium_mg')
    op.drop_column('nutrition_logs', 'potassium_mg')
    op.drop_column('nutrition_logs', 'cholesterol_mg')
    op.drop_column('nutrition_logs', 'omega6_g')
    op.drop_column('nutrition_logs', 'omega3_g')
    op.drop_column('nutrition_logs', 'polyunsaturated_fat_g')
    op.drop_column('nutrition_logs', 'monounsaturated_fat_g')
    op.drop_column('nutrition_logs', 'trans_fat_g')
    op.drop_column('nutrition_logs', 'saturated_fat_g')
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_vomiting_logs_user_id'), table_name='vomiting_logs')
    op.drop_index(op.f('ix_vomiting_logs_id'), table_name='vomiting_logs')
    op.drop_table('vomiting_logs')
    op.drop_index(op.f('ix_vitals_logs_user_id'), table_name='vitals_logs')
    op.drop_index(op.f('ix_vitals_logs_id'), table_name='vitals_logs')
    op.drop_table('vitals_logs')
    op.drop_index(op.f('ix_urination_logs_user_id'), table_name='urination_logs')
    op.drop_index(op.f('ix_urination_logs_id'), table_name='urination_logs')
    op.drop_table('urination_logs')
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_id'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_illness_logs_user_id'), table_name='illness_logs')
    op.drop_index(op.f('ix_illness_logs_id'), table_name='illness_logs')
    op.drop_table('illness_logs')
    op.drop_index(op.f('ix_health_conditions_user_id'), table_name='health_conditions')
    op.drop_index(op.f('ix_health_conditions_id'), table_name='health_conditions')
    op.drop_table('health_conditions')
    op.drop_index(op.f('ix_bowel_movements_user_id'), table_name='bowel_movements')
    op.drop_index(op.f('ix_bowel_movements_id'), table_name='bowel_movements')
    op.drop_table('bowel_movements')
    # ### end Alembic commands ###
