"""Add user personalization fields

Revision ID: 7c1bfa760608
Revises: 6cd11de19201
Create Date: 2026-02-14 03:39:57.539059
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7c1bfa760608'
down_revision: Union[str, None] = '6cd11de19201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender_at_birth', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('current_weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('target_weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('blood_type', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('preferred_units', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('food_intolerances', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dietary_restrictions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dietary_preferences', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('chronic_conditions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('family_history', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('fitness_goals', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('preferred_activities', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('exercise_frequency_per_week', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('smoking_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('alcohol_consumption', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sleep_schedule', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('stress_level', sa.String(length=50), nullable=True))
    
    # Add Boolean columns with server_default to avoid null constraint violation
    op.add_column('users', sa.Column('ai_coaching_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('ai_notification_preferences', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('ai_personality_preference', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('ai_language_complexity', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('data_sharing_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('ai_training_consent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_training_consent')
    op.drop_column('users', 'data_sharing_consent')
    op.drop_column('users', 'ai_language_complexity')
    op.drop_column('users', 'ai_personality_preference')
    op.drop_column('users', 'ai_notification_preferences')
    op.drop_column('users', 'ai_coaching_enabled')
    op.drop_column('users', 'stress_level')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'sleep_schedule')
    op.drop_column('users', 'alcohol_consumption')
    op.drop_column('users', 'smoking_status')
    op.drop_column('users', 'exercise_frequency_per_week')
    op.drop_column('users', 'preferred_activities')
    op.drop_column('users', 'fitness_goals')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'family_history')
    op.drop_column('users', 'chronic_conditions')
    op.drop_column('users', 'dietary_preferences')
    op.drop_column('users', 'dietary_restrictions')
    op.drop_column('users', 'food_intolerances')
    op.drop_column('users', 'allergies')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'preferred_units')
    op.drop_column('users', 'country')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'blood_type')
    op.drop_column('users', 'target_weight_kg')
    op.drop_column('users', 'current_weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'gender_at_birth')
    # ### end Alembic commands ###
