"""add_chronic_conditions_and_therapy_sessions

Revision ID: 8f23b3395540
Revises: c1d01355c0d8
Create Date: 2026-02-14 04:35:05.113442
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8f23b3395540'
down_revision: Union[str, None] = 'c1d01355c0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronic_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('CANCER', 'RENAL', 'DIABETES', 'BLOOD_DISORDER', 'CARDIOVASCULAR', 'RESPIRATORY', 'AUTOIMMUNE', 'NEUROLOGICAL', 'ENDOCRINE', 'OTHER', name='conditioncategory'), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', 'CRITICAL', 'REMISSION', name='conditionseverity'), nullable=False),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosed_by', sa.String(length=200), nullable=True),
    sa.Column('diagnosing_facility', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remission_date', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('current_treatment_plan', sa.Text(), nullable=True),
    sa.Column('primary_physician', sa.String(length=200), nullable=True),
    sa.Column('specialist_physician', sa.String(length=200), nullable=True),
    sa.Column('monitoring_frequency', sa.String(length=100), nullable=True),
    sa.Column('next_appointment', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronic_conditions_category'), 'chronic_conditions', ['category'], unique=False)
    op.create_index(op.f('ix_chronic_conditions_id'), 'chronic_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_chronic_conditions_is_active'), 'chronic_conditions', ['is_active'], unique=False)
    op.create_index(op.f('ix_chronic_conditions_user_id'), 'chronic_conditions', ['user_id'], unique=False)
    op.create_table('condition_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('metric_category', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('reference_range_min', sa.Float(), nullable=True),
    sa.Column('reference_range_max', sa.Float(), nullable=True),
    sa.Column('reference_range_text', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('measured_date', sa.DateTime(), nullable=False),
    sa.Column('measured_by', sa.String(length=200), nullable=True),
    sa.Column('test_method', sa.String(length=200), nullable=True),
    sa.Column('clinical_interpretation', sa.Text(), nullable=True),
    sa.Column('action_required', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['chronic_conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_metrics_condition_id'), 'condition_metrics', ['condition_id'], unique=False)
    op.create_index(op.f('ix_condition_metrics_id'), 'condition_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_condition_metrics_measured_date'), 'condition_metrics', ['measured_date'], unique=False)
    op.create_index(op.f('ix_condition_metrics_metric_name'), 'condition_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_condition_metrics_user_id'), 'condition_metrics', ['user_id'], unique=False)
    op.create_table('therapy_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('therapy_type', sa.Enum('DIALYSIS', 'HEMODIALYSIS', 'PERITONEAL_DIALYSIS', 'CHEMOTHERAPY', 'RADIATION_THERAPY', 'IMMUNOTHERAPY', 'TARGETED_THERAPY', 'HORMONE_THERAPY', 'INFUSION_THERAPY', 'PHYSICAL_THERAPY', 'OCCUPATIONAL_THERAPY', 'BLOOD_TRANSFUSION', 'PHOTOTHERAPY', 'OTHER', name='therapytype'), nullable=False),
    sa.Column('therapy_name', sa.String(length=200), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('total_sessions_planned', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'MISSED', 'RESCHEDULED', name='therapystatus'), nullable=False),
    sa.Column('facility_name', sa.String(length=300), nullable=True),
    sa.Column('facility_address', sa.String(length=500), nullable=True),
    sa.Column('attending_physician', sa.String(length=200), nullable=True),
    sa.Column('attending_nurse', sa.String(length=200), nullable=True),
    sa.Column('dialysis_access_type', sa.String(length=100), nullable=True),
    sa.Column('pre_dialysis_weight_kg', sa.Float(), nullable=True),
    sa.Column('post_dialysis_weight_kg', sa.Float(), nullable=True),
    sa.Column('fluid_removed_ml', sa.Float(), nullable=True),
    sa.Column('blood_flow_rate', sa.Float(), nullable=True),
    sa.Column('dialysate_flow_rate', sa.Float(), nullable=True),
    sa.Column('drugs_administered', sa.Text(), nullable=True),
    sa.Column('dosage', sa.String(length=200), nullable=True),
    sa.Column('route_of_administration', sa.String(length=100), nullable=True),
    sa.Column('radiation_dose_gy', sa.Float(), nullable=True),
    sa.Column('treatment_area', sa.String(length=200), nullable=True),
    sa.Column('pre_systolic_bp', sa.Integer(), nullable=True),
    sa.Column('pre_diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('post_systolic_bp', sa.Integer(), nullable=True),
    sa.Column('post_diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('pre_heart_rate', sa.Integer(), nullable=True),
    sa.Column('post_heart_rate', sa.Integer(), nullable=True),
    sa.Column('pre_temperature', sa.Float(), nullable=True),
    sa.Column('post_temperature', sa.Float(), nullable=True),
    sa.Column('oxygen_saturation', sa.Integer(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('adverse_reactions', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('patient_tolerance', sa.String(length=50), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('patient_notes', sa.Text(), nullable=True),
    sa.Column('next_session_scheduled', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['chronic_conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_sessions_condition_id'), 'therapy_sessions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_id'), 'therapy_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_scheduled_date'), 'therapy_sessions', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_status'), 'therapy_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_therapy_type'), 'therapy_sessions', ['therapy_type'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_user_id'), 'therapy_sessions', ['user_id'], unique=False)
    op.drop_column('users', 'chronic_conditions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chronic_conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_therapy_sessions_user_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_therapy_type'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_status'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_scheduled_date'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_condition_id'), table_name='therapy_sessions')
    op.drop_table('therapy_sessions')
    op.drop_index(op.f('ix_condition_metrics_user_id'), table_name='condition_metrics')
    op.drop_index(op.f('ix_condition_metrics_metric_name'), table_name='condition_metrics')
    op.drop_index(op.f('ix_condition_metrics_measured_date'), table_name='condition_metrics')
    op.drop_index(op.f('ix_condition_metrics_id'), table_name='condition_metrics')
    op.drop_index(op.f('ix_condition_metrics_condition_id'), table_name='condition_metrics')
    op.drop_table('condition_metrics')
    op.drop_index(op.f('ix_chronic_conditions_user_id'), table_name='chronic_conditions')
    op.drop_index(op.f('ix_chronic_conditions_is_active'), table_name='chronic_conditions')
    op.drop_index(op.f('ix_chronic_conditions_id'), table_name='chronic_conditions')
    op.drop_index(op.f('ix_chronic_conditions_category'), table_name='chronic_conditions')
    op.drop_table('chronic_conditions')
    # ### end Alembic commands ###
