"""add_user_roles_and_professional_profiles

Revision ID: b4499a525cca
Revises: e8db329c8b59
Create Date: 2026-02-15 02:51:19.119798
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'b4499a525cca'
down_revision: Union[str, None] = 'e8db329c8b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_role_assignments_id'), 'user_role_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_role'), 'user_role_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_table('professional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_assignment_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_state', sa.String(length=100), nullable=True),
    sa.Column('license_country', sa.String(length=100), nullable=True),
    sa.Column('license_expiry', sa.String(length=20), nullable=True),
    sa.Column('npi_number', sa.String(length=20), nullable=True),
    sa.Column('dea_number', sa.String(length=20), nullable=True),
    sa.Column('board_certifications', sa.Text(), nullable=True),
    sa.Column('medical_school', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('residency_program', sa.String(length=255), nullable=True),
    sa.Column('fellowship_program', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('sub_specialty', sa.String(length=200), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('practice_name', sa.String(length=255), nullable=True),
    sa.Column('practice_type', sa.String(length=100), nullable=True),
    sa.Column('practice_address', sa.Text(), nullable=True),
    sa.Column('practice_phone', sa.String(length=30), nullable=True),
    sa.Column('practice_email', sa.String(length=255), nullable=True),
    sa.Column('practice_website', sa.String(length=500), nullable=True),
    sa.Column('accepting_patients', sa.Boolean(), nullable=True),
    sa.Column('hospital_affiliations', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('clinical_languages', sa.Text(), nullable=True),
    sa.Column('telemedicine_available', sa.Boolean(), nullable=False),
    sa.Column('telemedicine_platforms', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('professional_bio', sa.Text(), nullable=True),
    sa.Column('publications', sa.Text(), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_assignment_id'], ['user_role_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_assignment_id', name='uq_profile_per_role')
    )
    op.create_index(op.f('ix_professional_profiles_id'), 'professional_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_professional_profiles_role_assignment_id'), 'professional_profiles', ['role_assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_profiles_role_assignment_id'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_id'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    # ### end Alembic commands ###
