"""Add privacy compliance and i18n support

Revision ID: c1d01355c0d8
Revises: 3e5633413cb9
Create Date: 2026-02-14 04:09:56.261638
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c1d01355c0d8'
down_revision: Union[str, None] = '3e5633413cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_category'), 'translations', ['category'], unique=False)
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_index(op.f('ix_translations_is_active'), 'translations', ['is_active'], unique=False)
    op.create_index(op.f('ix_translations_key'), 'translations', ['key'], unique=False)
    op.create_index(op.f('ix_translations_language_code'), 'translations', ['language_code'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('TERMS_OF_SERVICE', 'PRIVACY_POLICY', 'DATA_PROCESSING', 'DATA_SHARING_ANONYMIZED', 'DATA_SHARING_RESEARCH', 'MARKETING_COMMUNICATIONS', 'AI_COACHING', 'THIRD_PARTY_INTEGRATIONS', 'COOKIES_ANALYTICS', name='consenttype'), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('consent_granted', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('consent_language', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_consent_type'), 'consent_records', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consent_records_granted_at'), 'consent_records', ['granted_at'], unique=False)
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('data_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accessed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('accessed_by_system', sa.String(length=100), nullable=True),
    sa.Column('access_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('TREATMENT', 'AI_RECOMMENDATION', 'ANALYTICS_AGGREGATED', 'EXPORT_REQUEST', 'SUPPORT_REQUEST', 'LEGAL_COMPLIANCE', 'SECURITY_AUDIT', 'RESEARCH_ANONYMIZED', 'SYSTEM_MAINTENANCE', name='dataaccesspurpose'), nullable=False),
    sa.Column('data_accessed', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_access_logs_access_type'), 'data_access_logs', ['access_type'], unique=False)
    op.create_index(op.f('ix_data_access_logs_accessed_at'), 'data_access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_data_access_logs_accessed_by_user_id'), 'data_access_logs', ['accessed_by_user_id'], unique=False)
    op.create_index(op.f('ix_data_access_logs_id'), 'data_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_data_access_logs_purpose'), 'data_access_logs', ['purpose'], unique=False)
    op.create_index(op.f('ix_data_access_logs_user_id'), 'data_access_logs', ['user_id'], unique=False)
    op.create_table('data_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_full_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED', name='deletionstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retention_required', sa.Boolean(), nullable=True),
    sa.Column('retention_reason', sa.Text(), nullable=True),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('deletion_log', sa.JSON(), nullable=True),
    sa.Column('anonymization_log', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_deletion_requests_id'), 'data_deletion_requests', ['id'], unique=False)
    op.create_index(op.f('ix_data_deletion_requests_requested_at'), 'data_deletion_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_data_deletion_requests_status'), 'data_deletion_requests', ['status'], unique=False)
    op.create_index(op.f('ix_data_deletion_requests_user_id'), 'data_deletion_requests', ['user_id'], unique=False)
    op.create_table('data_export_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'DOWNLOADED', 'EXPIRED', 'FAILED', name='exportstatus'), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=True),
    sa.Column('include_attachments', sa.Boolean(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('download_url', sa.String(length=1000), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_export_requests_id'), 'data_export_requests', ['id'], unique=False)
    op.create_index(op.f('ix_data_export_requests_requested_at'), 'data_export_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_data_export_requests_status'), 'data_export_requests', ['status'], unique=False)
    op.create_index(op.f('ix_data_export_requests_user_id'), 'data_export_requests', ['user_id'], unique=False)
    op.create_table('privacy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allow_anonymized_analytics', sa.Boolean(), nullable=True),
    sa.Column('allow_collective_insights', sa.Boolean(), nullable=True),
    sa.Column('allow_research_participation', sa.Boolean(), nullable=True),
    sa.Column('allow_marketing_emails', sa.Boolean(), nullable=True),
    sa.Column('allow_product_updates', sa.Boolean(), nullable=True),
    sa.Column('allow_health_reminders', sa.Boolean(), nullable=True),
    sa.Column('ai_coaching_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_memory_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_explainability_level', sa.String(length=20), nullable=True),
    sa.Column('allow_third_party_integrations', sa.Boolean(), nullable=True),
    sa.Column('approved_third_parties', sa.JSON(), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('auto_delete_old_data', sa.Boolean(), nullable=True),
    sa.Column('allow_location_tracking', sa.Boolean(), nullable=True),
    sa.Column('allow_usage_analytics', sa.Boolean(), nullable=True),
    sa.Column('allow_crash_reporting', sa.Boolean(), nullable=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=True),
    sa.Column('health_data_visibility', sa.String(length=20), nullable=True),
    sa.Column('require_biometric_auth', sa.Boolean(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('gdpr_applies', sa.Boolean(), nullable=True),
    sa.Column('hipaa_applies', sa.Boolean(), nullable=True),
    sa.Column('data_residency_preference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_settings_id'), 'privacy_settings', ['id'], unique=False)
    op.create_index(op.f('ix_privacy_settings_user_id'), 'privacy_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_privacy_settings_user_id'), table_name='privacy_settings')
    op.drop_index(op.f('ix_privacy_settings_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    op.drop_index(op.f('ix_data_export_requests_user_id'), table_name='data_export_requests')
    op.drop_index(op.f('ix_data_export_requests_status'), table_name='data_export_requests')
    op.drop_index(op.f('ix_data_export_requests_requested_at'), table_name='data_export_requests')
    op.drop_index(op.f('ix_data_export_requests_id'), table_name='data_export_requests')
    op.drop_table('data_export_requests')
    op.drop_index(op.f('ix_data_deletion_requests_user_id'), table_name='data_deletion_requests')
    op.drop_index(op.f('ix_data_deletion_requests_status'), table_name='data_deletion_requests')
    op.drop_index(op.f('ix_data_deletion_requests_requested_at'), table_name='data_deletion_requests')
    op.drop_index(op.f('ix_data_deletion_requests_id'), table_name='data_deletion_requests')
    op.drop_table('data_deletion_requests')
    op.drop_index(op.f('ix_data_access_logs_user_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_purpose'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_accessed_by_user_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_accessed_at'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_access_type'), table_name='data_access_logs')
    op.drop_table('data_access_logs')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_granted_at'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_consent_type'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_translations_language_code'), table_name='translations')
    op.drop_index(op.f('ix_translations_key'), table_name='translations')
    op.drop_index(op.f('ix_translations_is_active'), table_name='translations')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_category'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
