"""add_community_health_tables

Revision ID: e8db329c8b59
Revises: b7d4e2f1a9c3
Create Date: 2026-02-15 01:29:22.358623
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'e8db329c8b59'
down_revision: Union[str, None] = 'b7d4e2f1a9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_health_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_reference_id', sa.String(length=200), nullable=True),
    sa.Column('affected_countries', sa.Text(), nullable=True),
    sa.Column('affected_regions', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=300), nullable=True),
    sa.Column('lot_numbers', sa.Text(), nullable=True),
    sa.Column('reason_for_recall', sa.Text(), nullable=True),
    sa.Column('recall_class', sa.String(length=20), nullable=True),
    sa.Column('disease_name', sa.String(length=200), nullable=True),
    sa.Column('pathogen', sa.String(length=200), nullable=True),
    sa.Column('confirmed_cases', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('target_population', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_health_alerts_category'), 'community_health_alerts', ['category'], unique=False)
    op.create_index(op.f('ix_community_health_alerts_id'), 'community_health_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_community_health_alerts_is_active'), 'community_health_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_community_health_alerts_severity'), 'community_health_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_community_health_alerts_source'), 'community_health_alerts', ['source'], unique=False)
    op.create_table('health_guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('target_population', sa.Text(), nullable=True),
    sa.Column('applicable_countries', sa.Text(), nullable=True),
    sa.Column('applicable_conditions', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_guidelines_category'), 'health_guidelines', ['category'], unique=False)
    op.create_index(op.f('ix_health_guidelines_id'), 'health_guidelines', ['id'], unique=False)
    op.create_index(op.f('ix_health_guidelines_is_current'), 'health_guidelines', ['is_current'], unique=False)
    op.create_index(op.f('ix_health_guidelines_source'), 'health_guidelines', ['source'], unique=False)
    op.create_table('alert_read_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['community_health_alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_read_status_alert_id'), 'alert_read_status', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_read_status_id'), 'alert_read_status', ['id'], unique=False)
    op.create_index(op.f('ix_alert_read_status_user_id'), 'alert_read_status', ['user_id'], unique=False)
    op.create_table('community_health_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('symptoms_reported', sa.Text(), nullable=True),
    sa.Column('number_affected', sa.Integer(), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('product_involved', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_health_reports_id'), 'community_health_reports', ['id'], unique=False)
    op.create_index(op.f('ix_community_health_reports_report_type'), 'community_health_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_community_health_reports_user_id'), 'community_health_reports', ['user_id'], unique=False)
    op.create_table('user_alert_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('countries', sa.Text(), nullable=True),
    sa.Column('severities', sa.Text(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_alert_subscriptions_id'), 'user_alert_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_alert_subscriptions_user_id'), 'user_alert_subscriptions', ['user_id'], unique=False)
    op.alter_column('breathing_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gratitude_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_media_assets_captured_at', table_name='media_assets')
    op.alter_column('mental_health_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mental_health_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_media_assets_captured_at', 'media_assets', ['captured_at'], unique=False)
    op.alter_column('gratitude_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('breathing_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_alert_subscriptions_user_id'), table_name='user_alert_subscriptions')
    op.drop_index(op.f('ix_user_alert_subscriptions_id'), table_name='user_alert_subscriptions')
    op.drop_table('user_alert_subscriptions')
    op.drop_index(op.f('ix_community_health_reports_user_id'), table_name='community_health_reports')
    op.drop_index(op.f('ix_community_health_reports_report_type'), table_name='community_health_reports')
    op.drop_index(op.f('ix_community_health_reports_id'), table_name='community_health_reports')
    op.drop_table('community_health_reports')
    op.drop_index(op.f('ix_alert_read_status_user_id'), table_name='alert_read_status')
    op.drop_index(op.f('ix_alert_read_status_id'), table_name='alert_read_status')
    op.drop_index(op.f('ix_alert_read_status_alert_id'), table_name='alert_read_status')
    op.drop_table('alert_read_status')
    op.drop_index(op.f('ix_health_guidelines_source'), table_name='health_guidelines')
    op.drop_index(op.f('ix_health_guidelines_is_current'), table_name='health_guidelines')
    op.drop_index(op.f('ix_health_guidelines_id'), table_name='health_guidelines')
    op.drop_index(op.f('ix_health_guidelines_category'), table_name='health_guidelines')
    op.drop_table('health_guidelines')
    op.drop_index(op.f('ix_community_health_alerts_source'), table_name='community_health_alerts')
    op.drop_index(op.f('ix_community_health_alerts_severity'), table_name='community_health_alerts')
    op.drop_index(op.f('ix_community_health_alerts_is_active'), table_name='community_health_alerts')
    op.drop_index(op.f('ix_community_health_alerts_id'), table_name='community_health_alerts')
    op.drop_index(op.f('ix_community_health_alerts_category'), table_name='community_health_alerts')
    op.drop_table('community_health_alerts')
    # ### end Alembic commands ###
